<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="checkDestination" name="DeployTeaseLib">

	<dirname property="DeployTeaseLib.basedir" file="${ant.file.DeployTeaseLib}"/>

    <local name="destination"/>
    <property name="destination" value=""/>

    <target name="checkDestination">
        <fail message="'destination' not set">
            <condition>
                <or>
                    <not><isset property="destination"/></not>
                    <equals arg1="${destination}" arg2=""/>
                </or>
            </condition>
        </fail>
    </target>

    <target name="createTeaseLibJar" depends="checkDestination">
        <jar destfile="${DeployTeaseLib.basedir}/lib/TeaseLib.jar">
            <fileset dir="${DeployTeaseLib.basedir}/bin">
           		<exclude name="simplelogger.properties"/>
           	</fileset>
        </jar>
    </target>

    <target name="deployTeaseLib" depends="checkDestination,createTeaseLibJar">
        <copy todir="${destination}/lib/">
            <fileset dir="${DeployTeaseLib.basedir}/lib/" excludes="models/,**.obj,**.iobj,**.pdb,**.ipdb,**.exp,**.ilk,**.lib"/>
            <fileset dir="${DeployTeaseLib.basedir}/lib/" includes="models/silero/"/>
            <fileset dir="${DeployTeaseLib.basedir}/lib/" includes="models/whisper/ggml-tiny.en-q4_0.bin"/>
            <fileset dir="${DeployTeaseLib.basedir}/lib/" includes="models/whisper/ggml-tiny.en-q4_0-en.bin"/>
            <fileset dir="${DeployTeaseLib.basedir}/lib/" includes="models/whisper/ggml-base.bin"/>
            <fileset dir="${DeployTeaseLib.basedir}/lib/" includes="models/whisper/ggml-base-en.bin"/>
            <fileset dir="${DeployTeaseLib.basedir}/lib/" includes="models/whisper/ggml-large-v3-turbo.bin"/>
            <fileset dir="${DeployTeaseLib.basedir}/lib/" includes="models/whisper/ggml-large-v3.bin"/>
        </copy>
        <copy todir="${destination}/pronunciation">
            <fileset dir="${DeployTeaseLib.basedir}/pronunciation"/>
        </copy>
    </target>

</project>
