/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_perception_HumanPose */

#ifndef _Included_teaselib_core_ai_perception_HumanPose
#define _Included_teaselib_core_ai_perception_HumanPose
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_ai_perception_HumanPose
 * Method:    setAspects
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_HumanPose_setAspects
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
