/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_deepspeech_DeepSpeechRecognizer */

#ifndef _Included_teaselib_core_ai_deepspeech_DeepSpeechRecognizer
#define _Included_teaselib_core_ai_deepspeech_DeepSpeechRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    languageCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_languageCode
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    decode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_decode
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    results
 * Signature: ()Lteaselib/core/ai/deepspeech/DeepSpeechRecognizer/Results;
 */
JNIEXPORT jobject JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_results
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    startRecognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_startRecognition
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    emulateRecognition
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_emulateRecognition
  (JNIEnv *, jobject, jstring);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    stopRecognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_stopRecognition
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
