/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_perception_SceneCapture */

#ifndef _Included_teaselib_core_ai_perception_SceneCapture
#define _Included_teaselib_core_ai_perception_SceneCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_ai_perception_SceneCapture
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_SceneCapture_init__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     teaselib_core_ai_perception_SceneCapture
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_SceneCapture_init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     teaselib_core_ai_perception_SceneCapture
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_SceneCapture_start
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_perception_SceneCapture
 * Method:    isStarted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_teaselib_core_ai_perception_SceneCapture_isStarted
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_perception_SceneCapture
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_SceneCapture_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
