/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_texttospeech_NativeVoice */

#ifndef _Included_teaselib_core_texttospeech_NativeVoice
#define _Included_teaselib_core_texttospeech_NativeVoice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_texttospeech_NativeVoice
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_texttospeech_NativeVoice_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
