/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_texttospeech_implementation_TeaseLibTTS */

#ifndef _Included_teaselib_core_texttospeech_implementation_TeaseLibTTS
#define _Included_teaselib_core_texttospeech_implementation_TeaseLibTTS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_texttospeech_implementation_TeaseLibTTS
 * Method:    newNativeInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_teaselib_core_texttospeech_implementation_TeaseLibTTS_newNativeInstance
  (JNIEnv *, jclass);

/*
 * Class:     teaselib_core_texttospeech_implementation_TeaseLibTTS
 * Method:    addLexiconEntry
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_texttospeech_implementation_TeaseLibTTS_addLexiconEntry
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     teaselib_core_texttospeech_implementation_TeaseLibTTS
 * Method:    getVoices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_teaselib_core_texttospeech_implementation_TeaseLibTTS_getVoices
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_texttospeech_implementation_TeaseLibTTS
 * Method:    setVoice
 * Signature: (Lteaselib/core/texttospeech/Voice;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_texttospeech_implementation_TeaseLibTTS_setVoice
  (JNIEnv *, jobject, jobject);

/*
 * Class:     teaselib_core_texttospeech_implementation_TeaseLibTTS
 * Method:    speak
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_texttospeech_implementation_TeaseLibTTS_speak__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     teaselib_core_texttospeech_implementation_TeaseLibTTS
 * Method:    speak
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_teaselib_core_texttospeech_implementation_TeaseLibTTS_speak__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     teaselib_core_texttospeech_implementation_TeaseLibTTS
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_texttospeech_implementation_TeaseLibTTS_stop
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_texttospeech_implementation_TeaseLibTTS
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_texttospeech_implementation_TeaseLibTTS_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
