/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_ComputeContext */

#ifndef _Included_teaselib_core_ai_ComputeContext
#define _Included_teaselib_core_ai_ComputeContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_ai_ComputeContext
 * Method:    newInstance
 * Signature: ()Lteaselib/core/ai/ComputeContext;
 */
JNIEXPORT jobject JNICALL Java_teaselib_core_ai_ComputeContext_newInstance
  (JNIEnv *, jclass);

/*
 * Class:     teaselib_core_ai_ComputeContext
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_ComputeContext_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
