/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_perception_DeepSpeechRecognizer */

#ifndef _Included_teaselib_core_ai_perception_DeepSpeechRecognizer
#define _Included_teaselib_core_ai_perception_DeepSpeechRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_ai_perception_DeepSpeechRecognizer
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_teaselib_core_ai_perception_DeepSpeechRecognizer_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     teaselib_core_ai_perception_DeepSpeechRecognizer
 * Method:    process
 * Signature: (Lteaselib/core/speechrecognition/SpeechRecognitionEvents;Ljava/util/concurrent/CountDownLatch;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_DeepSpeechRecognizer_process
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     teaselib_core_ai_perception_DeepSpeechRecognizer
 * Method:    languageCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_teaselib_core_ai_perception_DeepSpeechRecognizer_languageCode
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_perception_DeepSpeechRecognizer
 * Method:    startRecognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_DeepSpeechRecognizer_startRecognition
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_perception_DeepSpeechRecognizer
 * Method:    emulateRecognition
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_DeepSpeechRecognizer_emulateRecognition
  (JNIEnv *, jobject, jstring);

/*
 * Class:     teaselib_core_ai_perception_DeepSpeechRecognizer
 * Method:    stopRecognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_DeepSpeechRecognizer_stopRecognition
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_perception_DeepSpeechRecognizer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_DeepSpeechRecognizer_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
