/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_perception_Person */

#ifndef _Included_teaselib_core_ai_perception_Person
#define _Included_teaselib_core_ai_perception_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_ai_perception_Person
 * Method:    newNativeInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_teaselib_core_ai_perception_Person_newNativeInstance
  (JNIEnv *, jclass);

/*
 * Class:     teaselib_core_ai_perception_Person
 * Method:    update
 * Signature: (Lteaselib/core/ai/perception/Person;Lteaselib/core/ai/perception/HumanPose;Lteaselib/core/ai/perception/SceneCapture;IJ)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_Person_update__Lteaselib_core_ai_perception_Person_2Lteaselib_core_ai_perception_HumanPose_2Lteaselib_core_ai_perception_SceneCapture_2IJ
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jlong);

/*
 * Class:     teaselib_core_ai_perception_Person
 * Method:    update
 * Signature: (Ljava/util/List;Lteaselib/core/ai/perception/HumanPose;Lteaselib/core/ai/perception/SceneCapture;IJ)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_Person_update__Ljava_util_List_2Lteaselib_core_ai_perception_HumanPose_2Lteaselib_core_ai_perception_SceneCapture_2IJ
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jlong);

/*
 * Class:     teaselib_core_ai_perception_Person
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_Person_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
