/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_perception_HumanPose */

#ifndef _Included_teaselib_core_ai_perception_HumanPose
#define _Included_teaselib_core_ai_perception_HumanPose
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_ai_perception_HumanPose
 * Method:    init
 * Signature: (Lteaselib/core/ai/perception/SceneCapture;)J
 */
JNIEXPORT jlong JNICALL Java_teaselib_core_ai_perception_HumanPose_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     teaselib_core_ai_perception_HumanPose
 * Method:    setDesiredAspects
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_perception_HumanPose_setDesiredAspects
  (JNIEnv *, jobject, jint);

/*
 * Class:     teaselib_core_ai_perception_HumanPose
 * Method:    estimatePose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_teaselib_core_ai_perception_HumanPose_estimatePose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
