/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_jni_NativeObject */

#ifndef _Included_teaselib_core_jni_NativeObject
#define _Included_teaselib_core_jni_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_jni_NativeObject
 * Method:    disposeNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_jni_NativeObject_disposeNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
