/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_TeaseLibAI */

#ifndef _Included_teaselib_core_ai_TeaseLibAI
#define _Included_teaselib_core_ai_TeaseLibAI
#ifdef __cplusplus
extern "C" {
#endif
#undef teaselib_core_ai_TeaseLibAI_CAPTURE_DEVICE_POLL_DURATION_MILLIS
#define teaselib_core_ai_TeaseLibAI_CAPTURE_DEVICE_POLL_DURATION_MILLIS 5000i64
/*
 * Class:     teaselib_core_ai_TeaseLibAI
 * Method:    initOpenCL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_teaselib_core_ai_TeaseLibAI_initOpenCL
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_TeaseLibAI
 * Method:    sceneCaptures
 * Signature: ()Lteaselib/core/jni/NativeObjectList;
 */
JNIEXPORT jobject JNICALL Java_teaselib_core_ai_TeaseLibAI_sceneCaptures
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
