/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class teaselib_core_ai_deepspeech_DeepSpeechRecognizer */

#ifndef _Included_teaselib_core_ai_deepspeech_DeepSpeechRecognizer
#define _Included_teaselib_core_ai_deepspeech_DeepSpeechRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    newNativeInstance
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_newNativeInstance
  (JNIEnv *, jclass, jstring);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    languageCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_languageCode
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    setMaxResults
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_setMaxResults
  (JNIEnv *, jobject, jint);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    decode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_decode
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    results
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_results
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    setChoices
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_setChoices
  (JNIEnv *, jobject, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    startRecognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_startRecognition
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    emulate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_emulate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    stopRecognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_stopRecognition
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    stopEventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_stopEventLoop
  (JNIEnv *, jobject);

/*
 * Class:     teaselib_core_ai_deepspeech_DeepSpeechRecognizer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_teaselib_core_ai_deepspeech_DeepSpeechRecognizer_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
